### ISSUE TITLE
Missing 'use strict' from lib/asset-map.js

### ISSUE THREAD

**Issue by nandorstanko** [DockYard/ember-service-worker-asset-cache#16]
I got this error after installing the plugin:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Probably just a missing 'use strict' in ember-service-worker-asset-cache/lib/asset-map.js

**Comment by martndemus** [comment]
On it!

**Comment by martndemus** [comment]
Added it and published `0.6.0-beta.6`! :)
