### ISSUE TITLE
for fingerprint.prepend == "/", SW install crashes

### ISSUE THREAD

**Issue by mike-north** [DockYard/ember-service-worker-asset-cache#20]
## Version
`0.6.0`

## Test Case
in ember-cli-build.js

```js
let app = new EmberApp(defaults, {
   fingerprint: {
      prepend: '/'
   }
});
```

## Steps to reproduce
Install `ember-service-worker` and this addon

## Expected Behavior
I expect the service worker to install successfully

## Actual Behavior
Service worker install fails due to a `TypeError` on this line

https://github.com/DockYard/ember-service-worker-asset-cache/blob/master/service-worker/index.js#L11

When `PREPEND` (via options.fingerprint) has a value of "/", the following is not an allowed use of the URL constructor

```js
new URL(file, (PREPEND || self.location)).toString();
```

**Comment by eshtadc** [comment]
Confirmed that this error is still thrown
