### ISSUE TITLE
Usage for caching assets under multiple domains? 

### ISSUE THREAD

**Issue by AKST** [DockYard/ember-service-worker-asset-cache#22]
### Disclaimer

I know your `contributing.md` on questions says questions will be closed without comment, followed by a link to developer resources, but it's literally the contributor guide which offers no help at all, unless you're suggesting I develop a feature without prior discussion??? But I have no idea where else to post this?

------

So at the risk of this question being closed **immediately with out comment**, does this library offer a means of using it that allows me to cache all assets under multiple domains? As the following does not behave as anticipated.

```js
'asset-cache': {
  version: n,
  include: [
    'assets/**/*',
    'http://some.cdn.com/**/*',
  ],
}
```

What I was expecting was being able to cache assets from a CDN such as large images etc uploaded for profiles etc, but also static resources that run the site.

> If you must absolute close this due to your contributor guidelines could you at least direct me to somewhere, where someone where someone is prepared to answer this question? (just the contributing.md seemed pretty adamant about closing questions)

**Comment by martndemus** [comment]
The globs right now don't work on the actual URLS your assets are deployed to, but just on the contents of your `dist` folder. You can optionally specify the (CDN) url where your assets are hosted, but that's as far as the current set up goes. 

An option to make multiple domains possible would be to allow an url to be specified for each glob in the config.

**Comment by AKST** [comment]
Ahh our problem is our static assets will be cached one CDN, but we'll have stuff from 3rd parties stored on another domain. Maybe I'll implement my own service worker functionality to accomodate for this.

**Comment by martndemus** [comment]
@AKST If those are just a few files, you can use the manual option to specify urls to cache manually.
