### ISSUE TITLE
Refresh cache

### ISSUE THREAD

**Issue by villander** [DockYard/ember-service-worker-asset-cache#26]
How refresh cache, when i have a new build? I want update my cache, when my code is updated

This configuration never updates my application in the browser, even though I generate thousands of different builds

```
'asset-cache': {
      include: [
        'assets/**/*',
        'ember-welcome-page/images/*'
      ]
    }
```

**Comment by eshtadc** [comment]
If I understand it correctly, the cache is read in when the service worker installs so you have two options:

1. Force a new service worker by either setting your `versionStrategy` to 'every-build' per http://ember-service-worker.com/documentation/configuration/#versioning or just check the "Update on Reload" checkbox in the Application->Service Workers section of Chrome devtools (if its just a development painpoint)
2. Update the cache version to use by changing your `version` number in the config per instructions here: https://github.com/DockYard/ember-service-worker-asset-cache

**Comment by villander** [comment]
Thanks @eshtadc, it's solved my problem <3
