### ISSUE TITLE
consider not using es6 functions in index.js

### ISSUE THREAD

**Issue by shidel-dev** [DockYard/ember-service-worker-asset-cache#3]
I am getting the following on install.

`
  postprocessTree(type, tree) {
                 ^
`
`
Unexpected token (
`

I was on a older version of node (0.12.0).  I have updated the node version on the machine I was on, and this problem goes away due to newer versions of node supporting this syntax.  

your package.json declares that you support node engines ">= 0.10.0".  

I think that the required node version should be documented, if you do not intend to support them. I will make a pull with the fix if you do intend to support older versions.

**Comment by martndemus** [comment]
Merged the PR. Closing this.
