### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mydea** [DockYard/ember-service-worker-asset-cache#33]
Hey,

thanks for the great addon. Any chance to make a new release, to avoid the ember-cli-babel@5 deprecation warning? I see the dependency was already removed :)

**Comment by rwwagner90** [comment]
+1 for a new release please 😃

**Comment by knownasilya** [comment]
Same here, this is one of the addons with a babel v5 deprecation error at the latest release. A new release would fix that 👍

**Comment by larryh** [comment]
I'm with them.

BTW, thanks for the great addon!

**Comment by eshtadc** [comment]
Looks like this already happened with 0.6.9. Will be looking to do another shortly with updated dependencies.
