### ISSUE TITLE
sw-registration.js should not be cached by default (or at all?)

### ISSUE THREAD

**Issue by piotrpalek** [DockYard/ember-service-worker-asset-cache#8]
@martndemus I think this plugin shouldn't cache the `sw-registration.js` file by default, it trolled me a bit when I updated a registration file yet nothing changed.

If we don't cache it nothing bad will happen in case we're offline since it's included via a script tag (would just fail to load, already installed SW would still work), but we would have load that script every time when we're online.
Maybe an alternative could be to cache the script but have a SW check if the file changed and unregister if so?

I can try to work on a PR for that as well (just point me at how you would see this implemented in that case)

**Comment by martndemus** [comment]
With the newest release it's not included by default anymore!
